### ISSUE TITLE
Support Python schema definitions.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#26]
We should be leading with Python schema definitions, e.g. `json`, `str` or typed named tuples.

https://streamsxtopology.readthedocs.io/en/latest/streamsx.topology.schema.html#defining-a-stream-s-schema

**Comment by markheger** [comment]
shall `json`and `str` be mapped to CommonSchema`?

```
    py_types = {
        str: CommonSchema.String,
        json: CommonSchema.Json,
        }

    if schema in py_types:
        schema = py_types[schema]
```

**Comment by ddebrunner** [comment]
You can pass `json` and `str` directly as a schema parameter to topology methods, no need to have the layer above convert it.

**Comment by markheger** [comment]
> You can pass `json` and `str` directly as a schema parameter to topology methods, no need to have the layer above convert it.

No this doesn't work. Fails if not converted in upper layer.
```
Traceback (most recent call last):
  File "/home/streamsadmin/hostdir/git-public/pypi.streamsx.endpoint/package/streamsx/endpoint/tests/test_endpoint.py", line 95, in test_type_json_injection
    res = endpoint.inject(topo, name='jsoninject', monitor=None, context='sample', schema=json)
  File "/home/streamsadmin/hostdir/git-public/pypi.streamsx.endpoint/package/streamsx/endpoint/_endpoint.py", line 136, in inject
    _op = _HTTPInjection(topology, kind=kind, context=context, schema=schema, name=name, sslAppConfigName=sslAppConfigName)
  File "/home/streamsadmin/hostdir/git-public/pypi.streamsx.endpoint/package/streamsx/endpoint/_endpoint.py", line 223, in __init__
    super(_HTTPInjection, self).__init__(topology,kind,schema,params,name)
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/spl/op.py", line 299, in __init__
    super(Source,self).__init__(topology, kind, schemas=schema, params=params,name=name)
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/spl/op.py", line 202, in __init__
    super(Invoke,self).__init__(topology,kind,inputs,schemas,params,name)
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/topology/exop.py", line 37, in __init__
    self.__outputs(schemas)
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/topology/exop.py", line 74, in __outputs
    for schema in schemas:
TypeError: 'module' object is not iterable
```
